services:
  - type: web
    name: pico-bello-boq-frontend
    env: static
    region: oregon
    plan: starter
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false
